---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootesssops
  labels:
    app: springbootesssops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootesssops
  template:
    metadata:
      labels:
        app: springbootesssops
    spec:
      containers:
        - name: springbootesssops
          image: docker.io/phengbunath/springbootesssops:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
